version: "3"
services:
    www-nginx:
      build:
        context: nginx
        dockerfile: "Dockerfile"
      env_file:
        - .env
      restart: always
      networks:
        - default
        - uproda-proxy-network 
networks:
  uproda-proxy-network:
    external: true
